name: IceProtect
main: eu.icecraft.iceprotect.IceProtect
version: 2.0
depend: [WorldEdit, WorldGuard, iConomy]
commands:
  protect:
    description: General IceProtect command
    usage: /<command> <text>
  pr:
    description: General IceProtect command
    usage: /<command> <text>
  psell:
    description: Put a region up for sale
    usage: /<command> <text>